- name: Create Docker network
  community.docker.docker_network:
    name: app-network
    state: present
    docker_host: "unix:///var/run/docker.sock"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python