- name: Run proxy container
  community.docker.docker_container:
    name: proxy
    image: mariamarie/tp-devops-httpd:latest
    state: started
    restart_policy: always
    docker_host: "unix:///var/run/docker.sock"
    networks:
      - name: app-network
    ports:
      - "80:80"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python