# name: Docker CD

# on:
#   workflow_run:
#     workflows: ["Backend CI"]
#     types:
#       - completed

# jobs:
#   build-and-push:
#     if: >
#       github.event.workflow_run.conclusion == 'success' &&
#       github.event.workflow_run.head_branch == 'main'
#     runs-on: ubuntu-24.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.workflow_run.head_sha }}

#       - name: Login to DockerHub
#         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

#       - name: Build image and push backend
#         uses: docker/build-push-action@v6
#         with:
#           context: ./backend/simpleapi
#           push: true
#           tags: mariamarie/tp-devops-simple-api:latest

#       - name: Build image and push database
#         uses: docker/build-push-action@v6
#         with:
#           context: ./database
#           push: true
#           tags: mariamarie/tp-devops-database:latest

#       - name: Build image and push httpd
#         uses: docker/build-push-action@v6
#         with:
#           context: ./httpd
#           push: true
#           tags: mariamarie/tp-devops-httpd:latest

name: Docker CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  build-and-push:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend/simpleapi
          push: true
          tags: mariamarie/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: mariamarie/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: true
          tags: mariamarie/tp-devops-httpd:latest

  deploy:
    needs: build-and-push
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Setup SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H mchineaud.takima.school >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml