# name: CI devops 2025

# on:
#   push:
#     branches:
#       - main
#       - develop
#   pull_request:

# jobs:
#   test-backend:
#     runs-on: ubuntu-24.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: '21'

#       - name: Build and test with Maven
#         run: mvn clean verify --file ./backend/simpleapi/pom.xml

#       - name: Build, test and SonarCloud
#         run: >
#           mvn -B verify sonar:sonar
#           -Dsonar.projectKey=maria26045_Dockertp2-GIT-repo
#           -Dsonar.organization=maria26045
#           -Dsonar.host.url=https://sonarcloud.io
#           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#           --file ./backend/simpleapi/pom.xml

#   build-and-push-docker-image:
#     needs: test-backend
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-24.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Login to DockerHub
#         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

#       - name: Build image and push backend
#         uses: docker/build-push-action@v6
#         with:
#           context: ./backend/simpleapi
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

#       - name: Build image and push database
#         uses: docker/build-push-action@v6
#         with:
#           context: ./database
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

#       - name: Build image and push httpd
#         uses: docker/build-push-action@v6
#         with:
#           context: ./httpd
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
backend-ci.yml
docker-cd.yml