
# backend-ci.yml
# docker-cd.yml
name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # BACKEND
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend/simple-api
          push: true
          tags: mariamarie/tp-devops-simple-api:latest

      # DATABASE
      - name: Build & push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: mariamarie/tp-devops-database:latest

      # PROXY
      - name: Build & push proxy
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: true
          tags: mariamarie/tp-devops-httpd:latest


  deploy:
    needs: build   # ⚠️ ICI = nom du job au-dessus
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H mchineaud.takima.school >> ~/.ssh/known_hosts

      - name: Run Ansible
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml